### ISSUE TITLE
Failure when parsing unquoted keys

### ISSUE THREAD

**Issue by theduke** [fcoury/mongodb-language-model-rust#3]
```rust
// Works:
mongodb_language_model::parse(r#"{"a": 2}"#).unwrap()

// FAILS:
mongodb_language_model::parse(r#"{a: 1}"#).unwrap()
```

**Comment by fcoury** [comment]
Thanks for reporting! However the parser only works for valid JSON as input 😊

**Comment by theduke** [comment]
This should be clearly stated in the README/module docs then, because MongoDB queries do accept unquoted keys (aka are not valid JSON).

I'd understand not supporting if you were using a JSON parser, but since you use a custom parser why not support it?

**Comment by fcoury** [comment]
Do you have a specific use case in mind? The reason I am not supporting it today is mostly because I didn't need it.
